apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pods
  namespace: test
subjects:
- kind: User
  name: system:serviceaccount:test:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-creation
  apiGroup: rbac.authorization.k8s.io
